volumes:
  postgres-data:

services:
  postgres:
    image: postgres:17
    container_name: postgres
    shm_size: 2G
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./storage/restore.sh:/docker-entrypoint-initdb.d/restore.sh
      - ./storage/dump.bin:/dump.bin
    ports:
      - "5432:5432"
