name: Django CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: |
        cp .env.example.dev .env
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Start PostgreSQL
      run: |
        docker compose up -d
    - name: Wait for PostgreSQL to be ready
      run: |
        until docker exec postgres pg_isready -U $DB_USER -d $DB_NAME; do
          echo "Waiting for postgres..."
          sleep 3
        done
    - name: Run Tests
      run: |
        source venv/bin/activate
        python manage.py test
